const filters = [
  {
trigger: [" reddit", " site:reddit.com"],
  include: ["site:reddit.com"],
  exclude: []
},
{
    trigger: ["best books on"],
    include: [
      "site:brainpickings.org",
      "site:longreads.com",
      "site:nytimes.com",
      "site:theatlantic.com",
      "site:lithub.com",
      "site:blogspot.com",
      "site:penguinrandomhouse.com",
      "site:theexiledsoul.com",
      "site:theweek.com",
      "site:electricliterature.com",
      "site:keepingupwiththepenguins.com",
      "site:tckpublishing.com",
      "site:waterstones.com",
      "site:ninemagazine.org",
      "site:sandrasshelf.com",
      "site:bookroo.com",
      "site:fivebooks.com",
      "site:aboutgreatbooks.com",
      "site:hemibooks.com",
      "site:thebookhabit.co.uk",
      "site:lindasbookbag.com",
      "site:bookstr.com",
      "site:bestkidsbooks.com",
      "site:bookriot.com",
      "site:julias-books.com",
      "site:infobooks.org",
      "site:baos.pub",
      "site:publicbooks.org",
      "site:sobrief.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-site:goodreads.com",
      "-buzzfeed.com",
      "-pinterest.com",
      "-screenrant.com"
    ]
  },
   {
  trigger: [
    "best headphones",
    "best earbuds",
    "best audio interface",
    "best vocal mic",
    "best dynamic mic",
    "best condenser mic",
    "best studio monitors",
    "best speakers for mixing",
    "mic vs mic",
    "headphones vs monitors",
    "headphones",
    "speakers",
    "vs airpods",
    "vs bose",
    "vs sennheiser",
    "vs sony",
    "vs beats",
    "vs shure",
    "vs akg"
  ],
  include: [
    "site:soundguys.com",
    "site:headphonesty.com",
    "site:head-fi.org",
    "site:crinacle.com",
    "site:whathifi.com",
    "site:musicradar.com",
    "site:sonicscoop.com",
    "site:gearspace.com",
    "site:blogspot.com",
    "site:higherhz.com",
    "site:elektronauts.com",
    "site:soundonsound.com",
    "site:illmuzik.com",
    "site:audio46.com",
    "site:audiosciencereview.com",
    "site:homestudiobasics.com",
    "site:headphonesaddict.com",
    "site:audiophileon.com",
    "site:majorhifi.com",
    "site:thegreatestsong.com",
    "site:blog.gear4music.com/blog",
    "site:wordpress.com"
  ],
  exclude: [
    "-screenrant.com",
    "-buzzfeed.com",
    "-pinterest.com",
    "-quora.com",
    "-tomsguide.com",
    "-wegotthiscovered.com",
    "-cnet.com",
    "-lifewire.com",
    "-medium.com",
    "-reddit.com",
    "-youtube.com",
    "-ai-summary.com"
    ],
     ignoreIfShopping: true
  },
  {
    trigger: ["best tablesaw", "best table saw"],
    include: [
      "site:familyhandyman.com",
      "site:popularmechanics.com",
      "site:toolsinaction.com",
      "site:toolguyd.com",
      "site:protoolreviews.com",
      "site:bobvila.com",
      "site:thesharpcut.com",
      "site:sawmillcreek.org",
      "site:toolboxbuzz.com",
      "site:woodworkersjournal.com",
      "site:finewoodworking.com",
      "site:thespruce.com",
      "site:blogspot.com"
    ],
    exclude: [
      "-site:woodmagazine.com",
      "-pinterest.com",
      "-quora.com",
      "-buzzfeed.com",
      "-screenrant.com",
      "-tomsguide.com",
      "-wegotthiscovered.com"
    ]
  },
  {
    trigger: [
    "best camera",
    "best camera for street photography",
    "best film camera",
    "best lens for portraits",
    "dslr vs mirrorless",
    "film vs digital",
    "35mm vs 120",
    "ricoh vs fuji",
    "canon vs nikon",
    "vs sony",
    "vs leica",
    "vs fujifilm",
    "manual lens reviews",
    "vintage lens review",
    "best video camera",
    "best camera for filmmaking",
    "camera",
    "medium format",
    "camera lens",
    "nikon",
    "hasselblad",
    "leica",
    "pentax",
    "mamiya",
    "contax",
    "mionolta",
    "budget camera for youtube"	
  ],
  include: [
    "site:petapixel.com",
    "site:fstoppers.com",
    "site:35mmc.com",
    "site:japancamerahunter.com",
    "site:casualphotophile.com",
    "site:shotkit.com",
    "site:blog.analog.cafe",
    "site:emulsive.org",
    "site:blogspot.com",
    "site:dpreview.com",
    "site:lenspiration.com",
    "site:thephoblographer.com",
    "site:amateurphotographer.com",
    "site:kenrockwell.com",
    "site:eoshd.com",
    "site:amateurphotographer.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-youtube.com",
    "-screenrant.com",
    "-buzzfeed.com",
    "-tomsguide.com",
    "-cnet.com",
    "-pinterest.com",
    "-quora.com",
    "-photoworkout.com",
    "-thewirecutter.com",
    "-wegotthiscovered.com",
    "-ai-summary.com"
    ]
  },
  {
    trigger: ["best writing software", "best screenwriting software"],
    include: [
      "site:noamkroll.com",
      "site:indiewire.com",
      "site:johnaugust.com",
      "site:creativeindie.com",
      "site:nyfa.edu",
      "site:raindance.org",
      "site:scriptmag.com",
      "site:freelancewriting.com",
      "site:writingcooperative.com",
      "site:blog.reedsy.com",
      "site:blogspot.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-site:screencraft.org",
      "-site:finaldraft.com",
      "-screenrant.com",
      "-buzzfeed.com",
      "-quora.com",
      "-pinterest.com",
      "-upjourney.com",
      "-celtx.com",
      "-tomsguide.com",
      "-medium.com"
    ]
  },
  {
    trigger: ["best knife for home chefs", "best chef’s knife", "best chef knife"],
    include: [
      "site:thekitchn.com",
      "site:epicurious.com",
      "site:nytimes.com",
      "site:americastestkitchen.com",
      "site:splendidtable.org",
      "site:blogspot.com",
      "site:bonappetit.com",
      "site:eater.com",
      "site:nymag.com",
      "site:tasteofhome.com",
      "site:thespruceeats.com",
      "site:kitchenknifeforums.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-site:seriouseats.com",
      "-buzzfeed.com",
      "-quora.com",
      "-screenrant.com",
      "-tomsguide.com",
      "-themanual.com",
      "-wegotthiscovered.com",
      "-pinterest.com",
      "-producthunt.com",
      "-amazon.com",
      "-foodandwine.com"
    ]
  },
  {
    trigger: ["how to fix", "how to make", "how to build"],
    include: [
      "site:instructables.com",
      "site:familyhandyman.com",
      "site:thespruce.com",
      "site:howtogeek.com",
      "site:blogspot.com",
      "site:thisoldhouse.com",
      "site:homeserve.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-buzzfeed.com",
      "-screenrant.com",
      "-pinterest.com",
      "-quora.com",
      "-tomsguide.com",
      "-cnet.com"
    ]
  },
  {
    trigger: ["movies about", "films about", "best movies on", "best films about", "best films", "favorite movies", "forgotten movies", "favorite movies", "favorite silent films", "favorite silent movies", "favorite foreign films", "favorite foreign movies","favorite 30s movies", "favorite 40s movies", "favorite 50a movies", "favorite 60s movies", "favorite 90s movies", "favorite 80s movies", "favorite 70s movies", "favorite 2000s movies", "favorite 2010s movies", "favorite 2020s movies"],
    include: [
      "site:letterboxd.com",
      "site:sensesofcinema.com",
      "site:brightlightsfilm.com",
      "site:criterion.com",
      "site:rogerebert.com",
      "site:blogspot.com",
      "site:bfi.org.uk",
      "site:tasteofcinema.com",
      "site:flickeringmyth.com",
      "site:moviemezzanine.com",
      "site:lwlies.com",
      "site:lostinthemovies.com",
      "site:thepinksmoke.com",
      "site:pinnlandempire.com",
      "site:flaszonfilm.com",
      "site:thecinemaholic.com",
      "site:avclub.com",
      "site:filmsfatale.com",
      "site:jonathanrosenbaum.net",
      "site:rupertpupkinspeaks.wordpress.com",
      "site:sallitt.blogspot.com",
      "site:sallittfavorites.wordpress.com",
      "site:reverseshot.org", 
      "site:wordpress.com"
    ],
    exclude: [
      "-screenrant.com",
      "-wegotthiscovered.com",
      "-buzzfeed.com",
      "-collider.com",
      "-looper.com",
      "-rottentomatoes.com",
      "-pinterest.com"
    ]
  },
  {
    trigger: ["best books for", "books for people who", "books if you're"],
    include: [
     "site:brainpickings.org",
      "site:longreads.com",
      "site:nytimes.com",
      "site:theatlantic.com",
      "site:lithub.com",
      "site:blogspot.com",
      "site:penguinrandomhouse.com",
      "site:theexiledsoul.com",
      "site:theweek.com",
      "site:electricliterature.com",
      "site:keepingupwiththepenguins.com",
      "site:tckpublishing.com",
      "site:waterstones.com",
      "site:ninemagazine.org",
      "site:sandrasshelf.com",
      "site:bookroo.com",
      "site:fivebooks.com",
      "site:aboutgreatbooks.com",
      "site:hemibooks.com",
      "site:thebookhabit.co.uk",
      "site:lindasbookbag.com",
      "site:bookstr.com",
      "site:bestkidsbooks.com",
      "site:bookriot.com",
      "site:julias-books.com",
      "site:infobooks.org",
      "site:baos.pub",
      "site:publicbooks.org",
      "site:sobrief.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-goodreads.com",
      "-pinterest.com",
      "-buzzfeed.com",
      "-quora.com"
    ]
  },
  {
    trigger: ["what is", "explained", "meaning of", "define"],
    include: [
  "site:longreads.com",
  "site:aeon.co",
  "site:brainpickings.org",
  "site:theatlantic.com",
  "site:theconversation.com",
  "site:nautil.us",
  "site:psmag.com",
  "site:popula.com",
  "site:hazlitt.net",
  "site:believermag.com",
  "site:nplusonemag.com",
  "site:publicbooks.org",
  "site:commonwealmagazine.org",
  "site:scientificamerican.com",
  "site:psychologytoday.com",
  "site:greatergood.berkeley.edu",
  "site:blogspot.com",
  "site:philpapers.org", 
  "site:publicbooks.org",
  "site:nplusonemag.com",
  "site:blogspot.com",
  "site:wordpress.com"
],
    exclude: [
      "-wikipedia.org",
      "-buzzfeed.com",
      "-pinterest.com",
      "-quora.com"
    ],
  ignoreIfCalculator: true
  },
{
  trigger: [
    "writing software vs",
    "screenwriting app",
    "final draft vs",
    "fade in vs",
    "scrivener vs ulysses",
    "self publishing vs traditional publishing",
    "film editing software",
    "davinci resolve vs premiere",
    "creative cloud vs",
    "studio binder vs"
  ],
  include: [
    "site:writingcooperative.com",
    "site:raindance.org",
    "site:noamkroll.com",
    "site:indietalk.com",
    "site:creativeindie.com",
    "site:blog.reedsy.com",
    "site:prolost.com",
    "site:blog.finaldraft.com",
    "site:filmmakermagazine.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-ai-summary.com"
  ]
},
  {
    trigger: ["why do i", "why can't i", "why am i always", "why does it feel"],
    include: [
      "site:brainpickings.org",
      "site:theatlantic.com",
      "site:longreads.com",
      "site:aeon.co",
      "site:blogspot.com",
      "site:wordpress.com"
    ],
    exclude: [
      "-quora.com",
      "-reddit.com",
      "-psychologytoday.com",
      "-buzzfeed.com",
      "-pinterest.com",
      "-screenrant.com",
      "-verywellmind.com",
      "-clevelandclinic.org",
      "-mayoclinic.org"
    ]
  },
  {
    trigger: [
      "interview",
      "interview with",
      "profile",
      "conversation",
      "essay",
      "talks with",
      "q&a with",
      "longform",
      "retrospective",
      "deep dive",
      "old interview",
      "rare interview"
    ],
    include: [
      "site:baffler.com",
  "site:bbc.com",
  "site:believermag.com",
  "site:bfi.org.uk",
  "site:blogspot.com",
  "site:blogs.lse.ac.uk",
  "site:classic.esquire.com",
  "site:criterion.com",
  "site:democracynow.org",
  "site:esquire.com",
  "site:filmcomment.com",
  "site:filmmakermagazine.com",
  "site:foreignpolicy.com",
  "site:harpers.org",
  "site:harpersbazaar.com",
  "site:hazlitt.net",
  "site:indiewire.com",
  "site:interviewmagazine.com",
  "site:littlewhitelies.co.uk",
  "site:longreads.com",
  "site:lrb.co.uk",
  "site:movieweb.com",
  "site:mubi.com",
  "site:newyorker.com",
  "site:news.ycombinator.com",
  "site:nplusonemag.com",
  "site:npr.org",
  "site:nybooks.com",
  "site:reverse-shot.com",
  "site:rogerebert.com",
  "site:rollingstone.com",
  "site:scrapsfromtheloft.com",
  "site:sensesofcinema.com",
  "site:substack.com",
  "site:theatlantic.com",
  "site:theintercept.com",
  "site:theparisreview.org",
  "site:thequietus.com",
  "site:thetalkhouse.com",
  "site:tinhouse.com",
  "site:typepad.com",
  "site:vanityfair.com",
  "site:vault.si.com",
  "site:wordpress.com"
    ],
    exclude: [
    "-buzzfeed.com",
  "-screenrant.com",
  "-pinterest.com",
  "-wikipedia.org",
  "-imdb.com",
  "-celebritynetworth.com",
  "-famousbirthdays.com",
  "-youtube.com",
  "-tiktok.com",
  "-facebook.com",
  "-quora.com",
  "-linkedin.com",
  "-reddit.com",
  "-ai-summary.com"
    ]
  },
{
  trigger: [
    "how to fix",
    "how to build",
    "how to make",
    "best drill",
    "best tools",
    "best power tools",
    "best hand tools",
    "best tablesaw",
    "best circular saw",
    "saw blade",
    "best track saw",
    "best dust extractor",
    "best trim router",
    "best band saw",
    "domino alternative",
    "best orbital sander",
    "best sand paper",
    "best miter saw",
    "best chop saw",
    "best drill press",
    "best shop vac",
    "table saw jig",
    "shop jig",
    "work bench",
    "saw station",
    "drill bits",
    "router bits",
    "planer vs",
    "jointer vs",
    "vs drum sander",
    "corded vs cordless",
    "drill vs impact driver",
    "vs saw",
    "vs drill"
  ],
  include: [
    "site:familyhandyman.com",
    "site:popularmechanics.com",
    "site:thespruce.com",
    "site:toolsinaction.com",
    "site:toolguyd.com",
    "site:protoolreviews.com",
    "site:thisoldhouse.com",
    "site:woodmagazine.com",
    "site:instructables.com",
    "site:blogspot.com",
    "site:techgearlab.com",
    "site:bobvila.com",
    "site:finewoodworking.com",
    "site:sawmillcreek.org",
    "site:toolboxbuzz.com",
    "site:woodsmith.com",
    "site:thisoldhouse.com",
    "site:popularmechanics.com",
    "site:finehomebuilding.com",
    "site:kmtools.com",
    "site:jayscustomcreations.com",
    "site:731woodworks.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-tomsguide.com",
    "-wegotthiscovered.com",
    "-wikihow.com",
    "-cnet.com",
    "-reddit.com",
    "-youtube.com"
  ]
},
{
  trigger: [
    "best note-taking app",
    "best calendar app",
    "best productivity apps",
    "best task manager",
    "best writing app",
    "app for organizing",
    "to-do list app",
    "notion vs",
    "obsidian vs",
    "roam vs",
    "simplenote vs",
    "evernote vs",
    "trello vs",
    "project management app",
    "daily planner app",
    "best habit tracker",
    "best app for journaling",
    "tools to stay focused",
    "alternatives to notion",
    "vs todoist",
    "vs ticktick",
    "vs evernote"
  ],
  include: [
    "site:keepproductive.com",
    "site:theverge.com",
    "site:howtogeek.com",
    "site:macstories.net",
    "site:productivityist.com",
    "site:radreads.co",
    "site:fortelabs.co",
    "site:blog.obsidian.md",
    "site:roamresearch.com",
    "site:blogspot.com",
    "site:zapier.com",
    "site:techradar.com",
    "site:mumsnet.com",
    "site:macrumors.com",
    "site:learn.g2.com",
    "site:benchmarkreviews.com",
    "site:thesweetsetup.com",
    "site:betterapptech.com",
    "site:plaky.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-screenrant.com",
    "-buzzfeed.com",
    "-pinterest.com",
    "-quora.com",
    "-tomsguide.com",
    "-wegotthiscovered.com",
    "-makeuseof.com",
    "-medium.com",
    "-reddit.com",
    "-cnet.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "best IDE",
    "best code editor",
    "best text editor for programming",
    "vs code vs",
    "vscode vs",
    "sublime vs",
    "vim vs",
    "neovim vs",
    "webstorm vs",
    "framework vs",
    "react vs",
    "svelte vs",
    "vue vs",
    "vite vs",
    "webpack vs",
    "pnpm vs yarn",
    "static site generator",
    "javascript bundler",
    "node vs deno",
    "serverless vs containers"
  ],
  include: [
    "site:smashingmagazine.com",
    "site:dev.to",
    "site:css-tricks.com",
    "site:logrocket.com",
    "site:egghead.io",
    "site:frontstuff.io",
    "site:overreacted.io",
    "site:freecodecamp.org",
    "site:blog.risingstack.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-medium.com",
    "-hashnode.dev",
    "-sitepoint.com",
    "-geeksforgeeks.org",
    "-makeuseof.com",
    "-screenrant.com",
    "-buzzfeed.com",
    "-quora.com",
    "-tomsguide.com",
    "-reddit.com",
    "-cnet.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "best books on",
    "books to understand",
    "books for people who",
    "books if you liked",
    "book recommendations",
    "books to make you feel",
    "best essays",
    "reading list for",
    "books that changed your life",
    "books to learn",
    "how to self-educate",
    "books about being",
    "books for when you",
    "alternatives to goodreads"
  ],
  include: [
     "site:brainpickings.org",
      "site:longreads.com",
      "site:nytimes.com",
      "site:theatlantic.com",
      "site:lithub.com",
      "site:blogspot.com",
      "site:penguinrandomhouse.com",
      "site:theexiledsoul.com",
      "site:theweek.com",
      "site:electricliterature.com",
      "site:keepingupwiththepenguins.com",
      "site:tckpublishing.com",
      "site:waterstones.com",
      "site:ninemagazine.org",
      "site:sandrasshelf.com",
      "site:bookroo.com",
      "site:fivebooks.com",
      "site:aboutgreatbooks.com",
      "site:hemibooks.com",
      "site:thebookhabit.co.uk",
      "site:lindasbookbag.com",
      "site:bookstr.com",
      "site:bestkidsbooks.com",
      "site:bookriot.com",
      "site:julias-books.com",
      "site:infobooks.org",
      "site:baos.pub",
      "site:publicbooks.org",
      "site:sobrief.com",
      "site:wordpress.com"
  ],
  exclude: [
    "-goodreads.com",
    "-buzzfeed.com",
    "-pinterest.com",
    "-quora.com",
    "-screenrant.com",
    "-reddit.com",
    "-wegotthiscovered.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "how to take care of your mental health",
    "how to be okay alone",
    "how to get older",
    "how to make peace with",
    "how to age gracefully",
    "how to deal with loss",
    "why do I sabotage",
    "why do I ruin everything",
    "how to be less anxious",
    "books about getting older",
    "books about mental health",
    "essays on aging",
    "essays on grief",
    "how to be alone",
    "how to change"
  ],
  include: [
    "site:psychologytoday.com",
    "site:theatlantic.com",
    "site:longreads.com",
    "site:brainpickings.org",
    "site:npr.org",
    "site:harpers.org",
    "site:aeon.co",
    "site:believermag.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-wikihow.com",
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-wegotthiscovered.com",
    "-verywellmind.com",
    "-healthline.com",
    "-youtube.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "what is consciousness",
    "meaning of life",
    "essays on philosophy",
    "philosophy of",
    "what is free will",
    "what did nietzsche believe",
    "explain stoicism",
    "books on existentialism",
    "essays on death",
    "philosophy of identity",
    "philosophy of time",
    "stoicism vs nihilism",
    "existentialism vs absurdism",
    "camus vs kierkegaard",
    "nietzsche vs",
    "sartre vs"
  ],
  include: [
    "site:aeon.co",
    "site:brainpickings.org",
    "site:longreads.com",
    "site:theatlantic.com",
    "site:believermag.com",
    "site:philosophynow.org",
    "site:plato.stanford.edu",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-wikipedia.org",
    "-screenrant.com",
    "-buzzfeed.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-ai-summary.com",
    "-psychologytoday.com",
    "-wikihow.com"
  ]
},
{
 trigger: [
    "why do I always",
    "why do I push people away",
    "why do I self-sabotage",
    "attachment styles explained",
    "communication styles in relationships",
    "books about relationships",
    "books about toxic people",
    "how to get over someone",
    "what is emotional intimacy",
    "how to know if someone loves you",
    "how to set emotional boundaries",
    "essays on love",
    "essays on connection",
    "why do I ruin relationships",
    "why do I stay in bad relationships",
    "emotional boundaries in relationships",
    "essays about heartbreak",
    "books about emotional maturity"
  ],
  include: [
    "site:theatlantic.com",
    "site:longreads.com",
    "site:brainpickings.org",
    "site:thecut.com",
    "site:nymag.com",
    "site:hazlitt.net",
    "site:npr.org",
    "site:harpers.org",
    "site:believermag.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-verywellmind.com",
    "-healthline.com",
    "-wikipedia.org",
    "-ai-summary.com",
    "-psychologytoday.com"
  ]
},
{
  trigger: [
    "how to heal from",
    "how to heal from trauma",
    "how to be confident",
    "how to stop procrastinating",
    "how to be more productive",
    "how to know if someone likes you",
    "how to get closure",
    "why am I never satisfied",
    "how to stop overthinking",
    "how to wake up earlier",
    "how to beat procrastination",
    "how to be more organized"
  ],
  include: [
    "site:theatlantic.com",
    "site:longreads.com",
    "site:brainpickings.org",
    "site:aeon.co",
    "site:npr.org",
    "site:believermag.com",
    "site:hazlitt.net",
    "site:harpers.org",
    "site:blogspot.com",
    "site:health.clevelandclinic.org",
    "site:betterhealth.vic.gov.au",
    "site:helpguide.org",
    "site:nimh.nih.gov",
    "site:mayoclinic.org",
    "site:ptsd.va.gov",
    "site:ncbi.nlm.nih.gov",
    "site:westwindrecovery.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-verywellmind.com",
    "-healthline.com",
    "-wikipedia.org",
    "-cnet.com",
    "-ai-summary.com",
    "-youtube.com"
  ]
},
{
  trigger: [
    "travel essays",
    "essays on travel",
    "books about living abroad",
    "culture shock",
    "books about foreign countries",
    "language and identity",
    "essays on translation",
    "moving abroad for love",
    "learning a new language",
    "travel vs tourism",
    "japan vs korea travel",
    "books about being an outsider",
    "moving to another country",
    "expat vs immigrant"
  ],
  include: [
    "site:theatlantic.com",
    "site:longreads.com",
    "site:roadsandkingdoms.com",
    "site:nationalgeographic.com",
    "site:npr.org",
    "site:afar.com",
    "site:believermag.com",
    "site:translatorscafe.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-tripadvisor.com",
    "-reddit.com",
    "-wegotthiscovered.com",
    "-nomadicmatt.com",
    "-wikivoyage.org",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "why is everything expensive",
    "books about capitalism",
    "books about inequality",
    "essays on capitalism",
    "essays on economics",
    "labor vs capital",
    "minimum wage vs living wage",
    "finance for artists",
    "capitalism vs socialism",
    "how to think about money",
    "what causes recessions",
    "UBI vs welfare",
    "money and morality",
    "essays about class"
  ],
  include: [
    "site:theatlantic.com",
    "site:longreads.com",
    "site:npr.org",
    "site:jacobin.com",
    "site:currentaffairs.org",
    "site:dissentmagazine.org",
    "site:aeon.co",
    "site:believermag.com",
    "site:thebaffler.com",
    "site:hedgehogreview.com",
    "site:nybooks.com",
    "site:thewalrus.ca",
    "site:blogspot.com",
    "site:counterpunch.org",
    "site:mronline.org",
    "site:wordpress.com"
  ],
  exclude: [
    "-nerdwallet.com",
    "-investopedia.com",
    "-forbes.com",
    "-screenrant.com",
    "-buzzfeed.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-cnbc.com",
    "-medium.com",
    "-npr.org",
    "-ai-summary.com",
    "-youtube.com"
  ]
},
{
  trigger: [
    "best books on creativity",
    "essays on art",
    "how to find your art style",
    "why make art",
    "how to stay inspired",
    "visual thinking books",
    "minimalism vs maximalism",
    "illustration vs design",
    "what is good design",
    "philosophy of aesthetics",
    "creative process",
    "books about design thinking",
    "art vs commerce",
    "art vs",
    "creative process",
    "product and process",
    "creative process",
    "product vs process",
    "process vs product",
    "why design matters"
  ],
  include: [
    "site:brainpickings.org",
    "site:thecreativeindependent.com",
    "site:longreads.com",
    "site:itsnicethat.com",
    "site:eyeondesign.aiga.org",
    "site:designobserver.com",
    "site:printmag.com",
    "site:theatlantic.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-canva.com",
    "-99designs.com",
    "-pinterest.com",
    "-behance.net",
    "-dribbble.com",
    "-medium.com",
    "-screenrant.com",
    "-buzzfeed.com",
    "-quora.com",
    "-reddit.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "movies about",
    "films about",
    "best movies on",
    "essays on film",
    "screenwriting software",
    "books about filmmaking",
    "books about directing",
    "cinematography vs editing",
    "auteur theory",
    "film theory explained",
    "movies if you liked",
    "movies like",
    "directing vs writing",
    "movies about memory",
    "movies about grief",
    "scorsese vs",
    "spielberg vs",
    "kubrick vs"
  ],
  include: [
    "site:rogerebert.com",
    "site:sensesofcinema.com",
    "site:brightlightsfilm.com",
    "site:criterion.com",
    "site:indiewire.com",
    "site:filmcomment.com",
    "site:littlewhitelies.co.uk",
    "site:mubi.com",
    "site:blogspot.com",
    "site:bfi.org.uk",
    "site:tasteofcinema.com",
    "site:flickeringmyth.com",
    "site:moviemezzanine.com",
    "site:lwlies.com",
    "site:lostinthemovies.com",
    "site:thepinksmoke.com",
    "site:pinnlandempire.com",
    "site:flaszonfilm.com",
    "site:thecinemaholic.com",
    "site:avclub.com",
    "site:filmsfatale.com",
    "site:jonathanrosenbaum.net",
    "site:rupertpupkinspeaks.wordpress.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-screenrant.com",
    "-buzzfeed.com",
    "-collider.com",
    "-looper.com",
    "-wegotthiscovered.com",
    "-tomsguide.com",
    "-pinterest.com",
    "-cbr.com",
    "-reddit.com",
    "-youtube.com",
    "-ai-summary.com"
  ]
},
{
  trigger: ["list"],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-wegotthiscovered.com",
    "-tomsguide.com",
    "-collider.com",
    "-looper.com",
    "-quora.com",
    "-cbr.com",
    "-youtube.com",
    "-reddit.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "what's happening in",
    "explainer on",
    "analysis of",
    "why is rent high",
    "context for",
    "history of this policy",
    "law explained",
    "how did this happen",
    "supreme court ruling",
    "labor strikes",
    "election breakdown",
    "minimum wage debate"
  ],
  include: [
    "site:theatlantic.com",
    "site:npr.org",
    "site:propublica.org",
    "site:reuters.com",
    "site:bbc.com",
    "site:theintercept.com",
    "site:apnews.com",
    "site:foreignpolicy.com",
    "site:currentaffairs.org",
    "site:jacobin.com",
    "site:blogs.lse.ac.uk",
    "site:believermag.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-foxnews.com",
    "-cnn.com",
    "-msn.com",
    "-huffpost.com",
    "-nydailynews.com",
    "-dailywire.com",
    "-newsweek.com",
    "-thehill.com",
    "-theblaze.com",
    "-breitbart.com",
    "-buzzfeednews.com",
    "-screenrant.com",
    "-ai-summary.com",
    "-reddit.com",
    "-quora.com"
  ]
},
{
  trigger: ["review"],
  include: [
    "site:rogerebert.com",
    "site:nybooks.com",
    "site:sensesofcinema.com",
    "site:thequietus.com",
    "site:filmcomment.com",
    "site:criterion.com",
    "site:longreads.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-screenrant.com",
    "-collider.com",
    "-ign.com",
    "-buzzfeed.com",
    "-tomsguide.com",
    "-wegotthiscovered.com",
    "-techradar.com",
    "-cnet.com",
    "-gamespot.com",
    "-digitaltrends.com",
    "-theverge.com",
    "-ai-summary.com",
    "-rottentomatoes.com",
    "-metacritic.com",
    "-youtube.com",
    "-reddit.com"
  ]
},
{
  trigger: ["tips", "tricks", "hacks"],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-medium.com",
    "-tumblr.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-skillshare.com",
    "-reddit.com",
    "-youtube.com",
    "-lifehack.org",
    "-makeuseof.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "mental health",
    "how to feel better",
    "therapy tips",
    "how to sleep better",
    "how to heal from trauma",
    "wellness advice",
    "emotional wellness",
    "how to stop overthinking",
    "how to reduce anxiety",
    "burnout recovery"
  ],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-quora.com",
    "-pinterest.com",
    "-reddit.com",
    "-medium.com",
    "-tumblr.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-healthline.com",
    "-verywellmind.com",
    "-clevelandclinic.org",
    "-mayoclinic.org",
    "-webmd.com",
    "-ai-summary.com"
  ]
},
{
  trigger: ["music", "albums", "songs", "band", "artist", "music review"],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-genius.com",
    "-allmusic.com",
    "-pitchfork.com",
    "-consequence.net",
    "-rollingstone.com",
    "-uproxx.com",
    "-nme.com",
    "-stereogum.com",
    "-thefader.com",
    "-medium.com",
    "-ai-summary.com"
  ]
},
{
  trigger: [
    "study tips",
    "learning advice",
    "how to learn faster",
    "how to focus in school",
    "how to study better",
    "education advice",
    "teaching tips",
    "how to retain information",
    "learning styles",
    "best way to learn"
  ],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-medium.com",
    "-lifehack.org",
    "-makeuseof.com",
    "-collegeinfogeek.com",
    "-ai-summary.com",
    "-masterclass.com",
    "-udemy.com",
    "-skillshare.com"
  ]
},
{
  trigger: ["of all time"],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-medium.com",
    "-ai-summary.com"
  ]
},
  {
  trigger: ["film essays", "movie essays", "essays about film", "essays on cinema", "film criticism"],
  include: [
"site:rogerebert.com",
    "site:sensesofcinema.com",
    "site:brightlightsfilm.com",
    "site:criterion.com",
    "site:indiewire.com",
    "site:filmcomment.com",
    "site:littlewhitelies.co.uk",
    "site:mubi.com",
    "site:blogspot.com",
    "site:bfi.org.uk",
    "site:tasteofcinema.com",
    "site:flickeringmyth.com",
    "site:moviemezzanine.com",
    "site:lwlies.com",
    "site:lostinthemovies.com",
    "site:thepinksmoke.com",
    "site:pinnlandempire.com",
    "site:flaszonfilm.com",
    "site:thecinemaholic.com",
    "site:avclub.com",
    "site:filmsfatale.com",
    "site:jonathanrosenbaum.net",
    "site:rupertpupkinspeaks.wordpress.com",
    "site:longreads.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-youtube.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-ai-summary.com"
  ]
},
{
  trigger: ["recipe"],
  include: [],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-youtube.com",
    "-instagram.com",
    "-tiktok.com",
    "-facebook.com",
    "-linkedin.com",
    "-medium.com",
    "-ai-summary.com"
  ]
},

{
  trigger: ["freelance platform", "freelance platforms", "best freelance websites", "freelancer sites", "where to find freelance work", "gig economy sites"],
  include: [
    "site:freelancer.com",
    "site:upwork.com",
    "site:fiverr.com",
    "site:toptal.com",
    "site:peopleperhour.com",
    "site:weworkremotely.com",
    "site:flexjobs.com",
    "site:solidgigs.com",
    "site:remotive.io",
    "site:workingnomads.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-reddit.com",
    "-medium.com",
    "-quora.com",
    "-buzzfeed.com",
    "-screenrant.com",
    "-ai-summary.com"
  ]
},

{
  trigger: ["how to treat", "how to cure", "treatment for", "remedy for"],
  include: [
    "site:mayoclinic.org",
    "site:clevelandclinic.org",
    "site:webmd.com",
    "site:medlineplus.gov",
    "site:health.harvard.edu",
    "site:cdc.gov",
    "site:who.int",
    "site:nhs.uk"
  ],
  exclude: [
    "-quora.com",
    "-reddit.com",
    "-buzzfeed.com",
    "-verywellhealth.com",
    "-healthline.com",
    "-ai-summary.com"
  ]
},

{
  trigger: ["how to remove", "get rid of", "clean", "remove stain", "remove wine", "clean carpet", "remove smell"],
  include: [
    "site:thespruce.com",
    "site:thisoldhouse.com",
    "site:realsimple.com",
    "site:marthastewart.com",
    "site:familyhandyman.com",
    "site:cleanmama.com",
    "site:cleanipedia.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-reddit.com",
    "-wikihow.com",
    "-cnet.com",
    "-medium.com",
    "-ai-summary.com"
  ]
},

{
  trigger: [
    "clear cache", "free up storage", "free space", "speed up", "make faster",
    "optimize", "delete apps", "clear data", "restart", "reset", 
    "fix", "troubleshoot", "not working", "why won't", "why doesn’t",
    "how to reset", "how to fix", "won't turn on", "how to force quit"
  ],
  include: [
    "site:howtogeek.com",
    "site:macrumors.com",
    "site:anandtech.com",
    "site:theverge.com",
    "site:imore.com",
    "site:apple.com",
    "site:support.apple.com",
    "site:androidcentral.com",
    "site:blogspot.com",
    "site:wordpress.com"
  ],
  exclude: [
    "-buzzfeed.com",
    "-screenrant.com",
    "-pinterest.com",
    "-quora.com",
    "-wikihow.com",
    "-medium.com",
    "-cnet.com",
    "-tomsguide.com",
    "-makeuseof.com",
    "-lifewire.com",
    "-ai-summary.com"
  ]
},


{
  trigger: [
    "sports", "score", "team", "game", "match", "schedule", "playoffs", "season",  "draft", "tournament",
    "nba", "nfl", "mlb", "nhl", "ufc", "f1", "nascar", "ncaaf", "ncaab",
    "soccer", "football", "baseball", "basketball", "hockey", "tennis", "golf",
    "world cup", "super bowl", "finals", "olympics", "championship", "mvp",
  ],
  include: [],
  exclude: [
    "-youtube.com",
    "-tiktok.com",
    "-instagram.com",
    "-reddit.com",
    "-facebook.com",
    "-pinterest.com",
    "-tervis.com",
    "-tieguys.com",
    "-shomaizleather.com",
    "-www.petermillar.com",
    "-mms.com",
    "-tripadvisor.com",
    "-dooney.com",
    "-crocs.com",
    "-bradfordexchangechecks.com",
    "-m-clip.com",
    "-yeti.com",
    "-charlestyrwhitt.com",
    "-x.com",  
    "-nypost.com",
    "-shop.ty.com",
    "-inurl:reel",
    "-inurl:shorts",
    "filetype:html"
  ]
}


];

const fallbackFilter = {
  include: [],
  excludeDomains: [
    "ai-summary.com",    
    "buzzfeed.com",
    "screenrant.com",
    "pinterest.com",
    "reddit.com",
    "quora.com",
    "wegotthiscovered.com",
    "cnet.com",
    "youtube.com",
    "thecut.com",
    "nymag.com",
    "facebook.com",
    "instagram.com",
    "tiktok.com",
    "nypost.com",
    "foxnews.com",
    "wsj.com",
    "washingtonpost.com",
    "cnn.com",
    "msnbc.com",
    "justanswer.com",
    "rottentomatoes.com",
    "cosmopolitan.com",
    "medium.com"
  ],
  excludeQueryTerms: [
     "-inurl:reel",
  "-inurl:shorts",
  "-ai-summary.com",
  "-site:ai-summary.com",
  '-"AI Overview"',
  '-"AI-generated"',
  '-"AI answer"'
  ]
};

